### ISSUE TITLE
Compilation du .ino impossible

### ISSUE THREAD

**Issue by Didier-L** [f5soh/aeromodeling-throw-meter#1]
Bonjour,

Je souhaiterai construire votre montage électronique pour mesurer les angles. J'ai bien configuré Arduino avec les librairies additionnelles. Lors de la compilation de "Wifi_Angle_meter_mma8452_esp01.ino", la compilation s'arrête avec le message ci-dessous.

Que dois-je faire pour que la compilation fonctionne ?

A moins de télécharger directement le bin mais je ne sais pas dans ce cas comment faire.

Merci, cordialement,
Didier

C:\Users\Lanot\Documents\Diy_Mesure_debattements\aeromodeling-throw-meter-master\Wifi_Angle_meter_mma8452_esp01\Wifi_Angle_meter_mma8452_esp01.ino: In function 'void sendToSlave(int, byte, int)':
Wifi_Angle_meter_mma8452_esp01:468:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
  468 |   http.begin(slaveURL);
      |   ~~~~~~~~~~^~~~~~~~~~
C:\Users\Lanot\Documents\Diy_Mesure_debattements\aeromodeling-throw-meter-master\Wifi_Angle_meter_mma8452_esp01\Wifi_Angle_meter_mma8452_esp01.ino: In function 'void sendSlaveData()':
Wifi_Angle_meter_mma8452_esp01:456:13: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
  456 |   http.begin(serverURLData);
      |   ~~~~~~~~~~^~~~~~~~~~~~~~~
exit status 1
call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

**Comment by f5soh** [comment]
Bonjour Didier,
Les librairies ESP ont pas mal évolué depuis que j'ai écrit ce code, il faudrait le mettre à jour...
La solution est de rétrograder ces librairies dans une ancienne version (ex. 2.7) pour que le code actuel se compile.

Laurent

**Comment by Didier-L** [comment]
Bonjour Laurent,

Je viens de mettre la librairie esp en V2.7.0 et la programmation a fonctionné sans problème. Reste à faire le câblage pour tester.

Encore merci.

Didier

**Comment by f5soh** [comment]
Je viens d'ajouter un commit qui doit permettre de fonctionner avec les dernières librairies.

https://github.com/f5soh/aeromodeling-throw-meter/commit/42fc5d4e5d3c2e89fddd0a6a519f728f44ed5495
